[env:esp32-wrover-e]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.flash_mode = dio
board_build.psram = enabled

lib_deps =
    https://github.com/adafruit/Adafruit_MPU6050.git
    https://github.com/adafruit/Adafruit_Sensor.git
    madhephaestus/ESP32Servo @ ^3.0.5
